# -*- mode: ruby -*-
# vim: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  config.vm.provider :virtualbox do |v|
    #v.name = "rpm_hw"
    v.customize ["modifyvm", :id, "--memory", "4096"]
    v.customize ["modifyvm", :id, "--cpus", "4"]
  end

  config.vm.network :private_network, ip: "192.168.60.100"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provision "prov1", type: "shell", inline: <<-SHELL
  yum install -y redhat-lsb-core wget rpmdevtools rpm-build rpmdevtools createrepo yum-utils openssl-devel zlib-devel pcre-devel gcc nano mc groupinstall glibc-static tree httpd httpd-devel mod_ssl python2-certbot-apache vsftpd



  SHELL

  #config.vm.provision :shell, path: "rpm.sh"

end
